---
  munin_hosts:
    - {
        name: "localhost",
        address: "127.0.0.1",
        extra: ["use_node_name yes"]
      }
    - {
        name: "node1.test",
        address: "192.168.13.102",
        extra: ["use_node_name yes"]
      }
    - {
        name: "node2.test",
        address: "192.168.13.103",
        extra: ["use_node_name yes"]
      }
  munin_admin_user: munin
  munin_admin_password: munin
  munin_html_strategy: cron
  munin_graph_strategy: cron
  apache_mods_enabled:
    - rewrite.load
    - cgi.load
  apache_virtualhosts:
    - listening_ip: "*"
      listening_port: 80
      server_name: localhost
      document_root: /var/cache/munin/www
      _directories:
        - _root: /var/cache/munin/www
          Options: Indexes FollowSymLinks
          AllowOverride: None
          extra_directives: |
            Require all granted

      extra_directives: |
        LogLevel info
        ErrorLog {{ apache_log_dir }}/localhost-error.log
        CustomLog {{ apache_log_dir }}/localhost-access.log combined env=!dontlog

        RewriteEngine On
        RewriteCond %{HTTPS} off
        #RewriteRule (.*) http://%{HTTP_HOST}%{REQUEST_URI} [R=301,L]
